[[Task]]
name = "早安音乐"
time = "每天 07:00:00"
say = "早上好，$fn报时 $fn天气 一起来听音乐吧"
then = ["$fn播放音乐"]
after = ["$fn停止播放"]

[[Task]]
name = "提醒睡觉"
time = "每天 23:00:00"
say = "$fn报时 时间不早了，该睡觉啦"
then = ["$fn帮助入眠"]
after = ["30分钟", "$fn检测睡眠"]